ElbekDeveloper/CashOverflow

- CashOverflow/Brokers/Storages/IStorageBroker.Companies.cs
> BROKERS: Insert Company

- CashOverflow.Tests.Unit/Services/Foundations/Jobs/JobServiceTests.Logic.Add.cs
> CODE RUB: Fix Tabs #216

- CashOverflow/Brokers/Storages/IStorageBroker.Companies.cs
- CashOverflow/Brokers/Storages/StorageBroker.Companies.cs
> BROKERS: Delete Company 

- CashOverflow/Brokers/Storages/IStorageBroker.Companies.cs
- CashOverflow/Brokers/Storages/StorageBroker.Companies.cs
> BROKERS: Update Company

- .gitignore
- CashOverflow/Brokers/Storages/IStorageBroker.Companies.cs
- CashOverflow/Brokers/Storages/StorageBroker.Companies.cs
> BROKERS : Select Company By Id

- CashOverflow/Brokers/Storages/IStorageBroker.Companies.cs
- CashOverflow/Brokers/Storages/StorageBroker.Companies.cs
> BROKERS: Select All Company

- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Exceptions.Modify.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Logic.Modify.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Validations.Modify.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.cs
- CashOverflow/Models/Companies/Exceptions/CompanyDependencyException.cs
- CashOverflow/Models/Companies/Exceptions/CompanyServiceException.cs
- CashOverflow/Models/Companies/Exceptions/CompanyValidationException.cs
- CashOverflow/Models/Companies/Exceptions/FailedCompanyServiceException.cs
- CashOverflow/Models/Companies/Exceptions/FailedCompanyStorageException.cs
- CashOverflow/Models/Companies/Exceptions/InvalidCompanyException.cs
- CashOverflow/Models/Companies/Exceptions/LockedCompanyException.cs
- CashOverflow/Models/Companies/Exceptions/NotFoundCompanyException.cs
- CashOverflow/Models/Companies/Exceptions/NullCompanyException.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.Exception.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.Validation.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.cs
- CashOverflow/Services/Foundations/Companies/ICompanyService.cs
> FOUNDATIONS: Modify Company

- CashOverflow/Controllers/CompaniesController.cs
1. Happy Path
2. Validation Error
Closes #195
> CONTROLLERS: Post Company

- CashOverflow/Services/Foundations/Companies/ICompanyService.cs
> DOCUMENTATIONS: Add Exceptions for Company Add

- CashOverflow.Tests.Unit/Services/Foundations/Languages/LanguageServiceTests.Exceptions.Add.cs
> FOUNDATIONS:  Add Language

- CashOverflow/Controllers/CompaniesController.cs
> CONTROLLER: Put Company

- CashOverflow/Services/Foundations/Languages/ILanguageService.cs
> DOCUMENTATIONS: Add Exceptions for Language Service

- CashOverflow/Services/Foundations/Salaries/ISalaryService.cs
> DOCUMENTATIONS: Add Exceptions for Salary Service

- CashOverflow/Services/Foundations/Locations/ILocationService.cs
> DOCUMENTATIONS: Add Exceptions for Location Service

- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Exceptions.RemoveById.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Logic.RemoveById.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Validations.RemoveById.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.Exceptions.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.Validations.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.cs
- CashOverflow/Services/Foundations/Companies/ICompanyService.cs
> FOUNDATIONS: Remove Company by Id

- CashOverflow/Controllers/ReviewsController.cs
- CashOverflow/Startup.cs
> CONTROLLERS: Configure OData for Get Reviews Endpoint

- CashOverflow/Controllers/SalariesController.cs
> CONTROLLERS: Configure OData for Get All Salary Endpoint

- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Exceptions.RetrieveAll.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.Logic.RetrieveAll.cs
- CashOverflow.Tests.Unit/Services/Foundations/Companies/CompanyServiceTests.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.Exceptions.cs
- CashOverflow/Services/Foundations/Companies/CompanyService.cs
- CashOverflow/Services/Foundations/Companies/ICompanyService.cs
> FOUNDATIONS: Retrieve All Company

- CashOverflow/Controllers/CompaniesController.cs
Closes #204 
Deleted successfully
Not Found Error
> CONTROLLERS : Delete Company

- CashOverflow.Tests.Unit/Services/Foundations/Reviews/ReviewServiceTests.Exceptions.Add.cs
- CashOverflow/Models/Reviews/Exceptions/InvalidReviewReferenceException.cs
- CashOverflow/Services/Foundations/Reviews/ReviewService.Exceptions.cs
> FOUNDATIONS: Hande foreign key exception for add method of ReviewService

- .github/workflows/build.yml
- CashOverflow.Tests.Unit/CashOverflow.Tests.Unit.csproj
- CashOverflow/CashOverflow.csproj
- CashOverlow.Infrastructure.Build/CashOverflow.Infrastructure.Build.csproj
- CashOverlow.Infrastructure.Build/Program.cs
> INFRA: Upgrade .NET

- CashOverflow.Tests.Unit/Services/Foundations/Reviews/ReviewServiceTests.cs
- CashOverflow/Controllers/ReviewsController.cs
- CashOverflow/Migrations/20230709063837_ReviewsAddForeignKey.Designer.cs
- CashOverflow/Migrations/20230709063837_ReviewsAddForeignKey.cs
- CashOverflow/Models/Reviews/Review.cs
> CONTROLLERS: Handle Conflict on Post `Review`
